### ISSUE TITLE
entity 中 @Id 注解的问题

### ISSUE THREAD

**Issue by JingBiao-jb** [sunyue1380/QuickDAO3#1]
我在使用H2数据库开发一个简单的小项目。自定义实体，调用 dao.save()方法的时候报错。后发现是我对实体注解@Id理解有误，我实体中Id对因为数据库中主键Id，现实体中需要如下三种注解： @Id   @ColumnName(value = "ID") @Constraint(notNull=true, unique=true)。我想问一下@Id是否应该包含@Constraint(notNull=true, unique=true)这个属性？

**Comment by sunyue1380** [comment]
您好,感谢反馈.

#一句话反馈

使用了id注解后不用再加@Constraint(notNull=true, unique=true)

# 详细解答

我从您的叙述中,感觉您应该是数据库里表中主键的id列属性名为``ID``对吗? 那您只需要如下代码:
```
Class User{
   @Id
   @ColumnName("ID")
   long id;
}
```

您需要使用@ColumnName手动指定列名,因为QuickDAO采用的是驼峰式转下划线时,对于``ID``会自动转变为``id``

# 原理解释

## @Id注解

其实加上了@Id注解以后,就是在QuickDAO自动创建表的时候,会将该字段设置为自增字段.
在``cn.schoolwow.quickdao.builder.table.AbstractTableBuilder``类中有如下方法
```
public abstract String getAutoIncrementSQL(Property property);
```
该方法实际上就是返回各个数据库产品对应设置表外键的SQL语句.

## @Contraint注解
而对于@Constraint(notNull=true, unique=true),实际上就是添加非空约束和唯一性约束,目前为止,QuickDAO所支持的数据库产品对应的SQL语句都是一致的.其对应的方法也在``cn.schoolwow.quickdao.builder.table.AbstractTableBuilder``类中
```
public void createIndex(Entity entity, IndexType indexType) throws SQLException
```

而**数据库主键是否就是添加了非空约束和唯一性约束**,这个也和具体的数据库产品有关.在``cn.schoolwow.quickdao.builder.table.AbstractTableBuilder``类中的如下方法
```
public abstract Entity[] getDatabaseEntity() throws SQLException;
```
会获取各个数据库对应的字段信息,目前v3.1版本暂时还未加上获取字段约束相关的代码,但是在v3.2的快照版已经添加上了,v3.2的正式版会添加获取字段约束相关的代码.

# 最后
QuickDAO一直在不断更新中,有什么问题和反.馈目前版本V3.1,计划1月份发布v3.2版本.欢迎提交Issue,作者将看到后的第一时间回复哈,感谢支持.

**Comment by sunyue1380** [comment]
题主如果觉得好用麻烦也向朋友推荐一下哈，拿来做做小项目还是很惬意的。

**Comment by JingBiao-jb** [comment]
> 您好，感谢反馈。
> 
> ＃一句话反馈
> 
> 使用了id注解后不用再加@constraint（notNull = true，unique = true）
> 
> # 详细解答
> 我从您的叙述中，感觉您应该是数据库里表中主键的id列属性称为`ID`对吗？那您只需要如下代码：
> 
> ```
> Class User{
>    @Id
>    @ColumnName("ID")
>    long id;
> }
> ```
> 
> 您需要使用@ColumnName手动指定列名，因为QuickDAO采用的是驼峰式转下划线时，对于`ID`会自动转换为`id`
> 
> # 原理解释
> ## @id注解
> 其实加上了@id注解以后，就是在QuickDAO自动创建表的时候，会转换为自增细分。
> 在`cn.schoolwow.quickdao.builder.table.AbstractTableBuilder`类中有如下方法
> 
> ```
> public abstract String getAutoIncrementSQL(Property property);
> ```
> 
> 该方法实际上就是返回各个数据库产品对应的设置表外键的SQL语句。
> 
> ## @Contraint注解
> 而对于@constraint（notNull = true，unique = true），实际上就是添加非空约束和唯一性约束，目前为止，QuickDAO所支持的数据库产品对应的SQL语句都是一致的。`cn.schoolwow.quickdao.builder.table.AbstractTableBuilder`类中
> 
> ```
> public void createIndex(Entity entity, IndexType indexType) throws SQLException
> ```
> 
> 而**数据库主键是否就是添加了非空约束和唯一性约束**，这个也和具体的数据库产品有关。在`cn.schoolwow.quickdao.builder.table.AbstractTableBuilder`类中的如下方法
> 
> ```
> public abstract Entity[] getDatabaseEntity() throws SQLException;
> ```
> 
> 会获取各个数据库对应的分区信息，目前v3.1版本暂时没有重新获取获取约束相关的代码，但是在v3.2的快照版本已经添加上了，v3.2的正式版会添加获取限制相关的代码。
> 
> # 最后
> QuickDAO一直在不断更新中，有什么问题和反。馈送当前版本V3.1，计划1月份发布v3.2版本。欢迎提交问题，作者将看到后的第一时间回复哈，感谢支持。


感谢您的耐心解答
按照您的说法，我重新试了一下。由程序生成的表是可以的实现id为主键的自增序列。
我目前的数据库中存在旧数据，主键为ID，是由程序自动生成的Long类型的数字，不想要自增序列座组件的情况下，我对代码修改如下，测试可以实现功能。请问是否可以，或者是否有更好的实现方式。
 ```
 class UserService{

    @Autowired
    ApplicationContext applicationContext;

   public void demo(String jsonData) {
      DAO dao = QuickDAO.newInstance()
                  .dataSource(applicationContext.getBean(BasicDataSource.class))
                  .packageName("com.jingbiao.user.entity")
                  **.autoCreateProperty(false)**
                  .build();
     UserEntity user = new UserEntity();
     user.setUid();//调用其他方法生成id
     dao.insert(user);
   }
}
 class UserEntity{
    @Id
    private long id;
    @ColumnName(value = "ID")
    @Constraint(notNull = true,unique = true)
    private long uid;
}
 ```
**因为@Id注解是必要的，我使用了一个“不生效的主键字段”来代替他，而我真实的主键字段我修改为了uid。
@Constraint(notNull = true,unique = true) 又是必须的，否则 dao.save()方法中 cn.schoolwow.quickdao.builder.sql selectByUniqueKey方法会导致 select 语句不包含 where id=? 的条件
**

**Comment by sunyue1380** [comment]
@JingBiao-jb

我明白您的意思了,您相当于是想要自己手动管理id的生成,但是又需要QuickDAO将这个属性设置为自动增长,所以会存在您这样的一个解决方案.

# 解决方案
目前QuickDAO的方案是基于自增Id的,会将@Id注解标识的属性作为id属性,并且设置自增属性.当前版本(v3.1)暂时只能按照您的代码中变通的处理一下了.在v3.2的版本中,我会这么处理,在@Id注解添加一个属性autoCrement属性,表明主键id是否需要自增还是只需要创建一个普通的属性.

v3.2版本的解决方案
```
class UserEntity{
   @Id(autoCrement=false)
   @ColumnName(value = "ID")
   private long id;
}
```
同时对于标识为id的属性就自动设置它为notNull和unique的,不用用户再手动设置了.

感谢反馈哈,这个问题暂时只能在v3.2的版本中解决了.

另外再补充一下insert,update,save方法的区别
* insert: 直接执行插入语句
* update: 执行更新语句(有唯一性约束根据唯一性约束更新,否则根据id更新,若都没有则忽略该操作)
* save: 先判断记录是否存在(若对应实体表有唯一性约束就根据唯一性约束查,若没有再判断是否有id,若id也没有则认为记录不存在),存在的话就更新(同样有唯一性约束根据唯一性约束更新,否则根据id更新),不存在的话就插入

**Comment by JingBiao-jb** [comment]
感谢您的耐心解答，期待QuickDAO新版本的到来。
