### ISSUE TITLE
cn.schoolwow.quickdao.dao. AbstractDAO中构造方法

### ISSUE THREAD

**Issue by JingBiao-jb** [sunyue1380/QuickDAO3#2]
我想对 cn.schoolwow.quickdao.dao. AbstractDAO  二次开发，需要继承该类的时候，需要一个无参的构造方法，但我看到源代码中只有 有参的构造方法。
我的想法是这样的。
我理解的每一个Dao 是对应每一个Entity的。我在使用框架springboot开发用户功能时，希望对用户的操作都通过UserDao 来完成增删改查。
```
@Repository
public class UserDao {

    private DAO dao = null;

    public UserDao() {
    }

    @Autowired
    public UserDao(ApplicationContext applicationContext) {
        dao = QuickDAO.newInstance()
                .dataSource(applicationContext.getBean(BasicDataSource.class))
                .packageName(UserEntity.class.getPackage().getName())
                .autoCreateProperty(false)
                .build();
    }

    public int save(Object instance) {
        return dao.save(instance);
    }

}
```
如果我继承类AbstractDAO  后，需要在UserDao中实现父类构造方法，这时候我需要一个无参的构造方法。如果可以实现继承的话，我也不需要重写UserDao.save()方法。
如果我的想法有什么不合适的地方，还望指正。

**Comment by sunyue1380** [comment]
您好,如果您一定要针对User表编写一个UserDAO类,目前就只能您手动的自己编写UserDAO层了.

QuickDAO的设计理念就是所有的数据库操作只需要跟一个dao对象交互即可.

> 每一个Dao是对应每一个Entity

这种观念在QuickDAO中是不存在的.dao对象是支持多线程的,您可以在多线程环境下使用dao对象

我不知道您的使用场景是什么,但是QuickDAO的一大优势就是彻底抛弃所谓的DAO层,您现在的思维其实跟Mybatis框架的思维是一样的.我本人也使用过Mybatis,但是当项目做多了,便越发觉得Mybatis过度设计,没必要整出一个DAO层.这里有一篇文章您可以参考 [为什么我劝你放弃mybatis](https://zhuanlan.zhihu.com/p/45044649)

另外AbstractDAO类并不是用来设计为被继承的,继承它是没有意义的,QuickDAO的设计理念就是所有数据库操作只通过一个DAO对象即可.

**Comment by JingBiao-jb** [comment]
感谢您的回复，让我对QuickDAO的认识又加深了。
根据您的建议，我决定放弃之前的想法，根据您的建议完善我的代码，我觉得这是一个可行的尝试。由于我是给公司内部做项目，想法会局限一些，您的回复也提示了我这一点，这也是我本来做我这个项目的意思，再次感谢您提供给我的思想。
