### ISSUE TITLE
一对多的关系怎么表示

### ISSUE THREAD

**Issue by singlet264** [sunyue1380/QuickDAO3#3]
如题:

**Comment by sunyue1380** [comment]
以下例子,例如一个User对应多个Address

```
public class Address{
   private long id;
   private long userId; //一个Address关联一个用户
   private User user;//对应的用户实体类
}

public class User{
   private long id;
}
```
查询的时候这样写:
```
List<Address> addressList = dao.query(Address.class)
                         .joinTable(User.class,"userId","id") //参数含义 Address.userId = User.id
                         .done()
                         .compositField() //如果需要返回结果填充Address类的user成员变量的话
                         .execute()
                        .getList();        
```
此外，QuickDAO还支持多次关联 例如Address类又关联City类
```
public class City{
   private long id;
   private long addressId; //一个City对应一个Address
   private Address addressr;//对应的Address类
}
```

多次关联的例子:
```
List<City> addressList = dao.query(City.class)
                         .joinTable(Address.class,"addressId","id") //参数含义 City.addressId= Address.id
                         .joinTable(User.class,"userId","id") //参数含义 Address.userId= user.id
                         .done()
                         .compositField() //如果需要返回结果填充Address类的user成员变量的话
                         .execute()
                        .getList();       
```

`` .joinTable(Address.class,"addressId","id")``  join Address表就"进入了"Address表,``done()``方法返回主表(City),doneSubcondition返回父表(Address).

更加具体的文档，您可以查看[点击这里查看](https://sunyue1380.github.io/QuickDAO3/#/zh-cn/select/joinTable)

**Comment by singlet264** [comment]
```
public class User {
    private String uesrname;
    private List<Address> addressList;
}
```
还不支持这种吗？

**Comment by singlet264** [comment]
对了  请问能返回自增长id吗

**Comment by singlet264** [comment]
项目很不错，用来快速构建小项目还是很方便，希望继续改进，加油！！！奥里给

**Comment by sunyue1380** [comment]
@Heemooo  
```
public class User {
    private String uesrname;
    private List<Address> addressList;
}
```
这种形式框架来实现实际上有一定难度的，我当初来设计此框架的时候也想到了这一点，但是实际实现起来是很麻烦的。（需要集合级别的关联查询，比如Addrss类又关联了City）实现起来复杂度很高。

但是这种形式您可以手动的去实现.如我上面所诉，您可以手动查询addressList 列表出来再设置进去即可，就是把您原来期望的一步完成分成了两步完成，其实影响并不大，而且更灵活。

--------------------------------------------
关于自增id，您只需要在long型(目前自增id只支持long型)的字段注解@Id注解即可，您可以[点此查看文档](https://sunyue1380.github.io/QuickDAO3/#/zh-cn/config/annotation)

id的部分也可以您自己控制。

------------------------------------------------
建议您先看一下项目文档哈，篇幅不是很长，我想应该可以解答您现有的大部分疑惑。

项目文档地址 :  https://sunyue1380.github.io/QuickDAO3/

觉得好用也麻烦您给身边的同事推荐一下哈。因为项目目前其实使用人数少，所以很多问题其实可能还没暴露出来，需要大家的积极反馈哈，谢谢啦。
