### ISSUE TITLE
关于新建Dao对象的问题

### ISSUE THREAD

**Issue by iceBear67** [sunyue1380/QuickDAO3#4]
> //指定实体所在包名
cn.schoolwow.quickdao.dao.DAO dao = QuickDAO.newInstance()
                    .dataSource(mysqlDataSource)
                    .packageName("cn.schoolwow.quickdao.entity")
                    .build();
//之后所有的操作使用dao对象完成

这里指定了一个cn.schoolwow.quickdao.entity，意思是
```java
User user = dao.fetch(User.class,1);
```
的User.class必须要在里面吗？或者他是干什么用的?

**Comment by iceBear67** [comment]
因为只凭class也能获取到包名所以我对这个参数有点不明觉厉......

**Comment by iceBear67** [comment]
看了一下，大概是扫描后自动建表？那问题就是..他会扫子目录里面的类吗

**Comment by sunyue1380** [comment]
@iceBear67  会的。QuickDAO可以扫描子目录中的类。
具体文档可以查看[这里](https://sunyue1380.github.io/QuickDAO3/#/zh-cn/config/mapping)

**Comment by sunyue1380** [comment]
@iceBear67 配置packageName("cn.schoolwow.quickdao.entity") 后，QuickDAO会扫描该包下面的所有实体类并且在数据库中建立对应的表。  User类是必须在配置扫描的包路径下的，否则数据库里不会建立User表。

**Comment by iceBear67** [comment]
@sunyue1380 非常感谢，现在明白了
