### ISSUE TITLE
jar包找不到

### ISSUE THREAD

**Issue by weststarqp** [sunyue1380/QuickDAO3#5]
<dependency>
            <groupId>commons-dbcp</groupId>
            <artifactId>commons-dbcp</artifactId>
            <version>1.4</version>
        </dependency>
        <dependency>
            <groupId>cn.schoolwow</groupId>
            <artifactId>QuickDAO</artifactId>
            <version>3.3</version>
        </dependency>
根本找不到jar

**Comment by sunyue1380** [comment]
中央仓库已经查询得到此jar，麻烦看一下你自己的配置是否哪里有问题吧

https://mvnrepository.com/artifact/cn.schoolwow/QuickDAO/3.3
